In [2]:
import pandas as pd
import numpy as np

# 1- Load data  file

In [4]:
df = pd.read_csv('imports/googleplaystore.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# 2- Perform Initial operations on dataset

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [6]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [7]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [8]:
df.shape

(10841, 13)

In [9]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [10]:
df.sample(4)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5740,Analog Clock AW Plus-7,TOOLS,4.2,725,3.0M,"100,000+",Free,0,Everyone,Tools,"March 14, 2018",2,4.3 and up
10667,Bullet - FN Theme,PERSONALIZATION,3.8,143,240k,"5,000+",Free,0,Everyone,Personalization,"July 31, 2013",1,2.2 and up
5683,SMS Au revoir,FAMILY,NaN,17,1.7M,"5,000+",Free,0,Everyone,Entertainment,"January 15, 2018",2.0.0,4.0 and up
2175,Whoowasit? - Best kids game!,FAMILY,4.0,248,26M,"5,000+",Paid,$2.99,Everyone,Board;Action & Adventure,"July 24, 2018",1.6,4.1 and up

In [11]:
df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

# 3- Perform pre-processing steps (Handle Missing values, Data type transformation)
  ## 3.a fill NaN and null values with N/A
  ## 3.b format the Price column as float
  ## 3.c introduce a new Currency column with USD value
  ## 3.d format the Last Updated column as ISO date string
# 4- Analyze all the columns

In [13]:
df['Rating'] = df['Rating'].fillna('N/A')

In [19]:
df['Type'] = df['Type'].fillna('N/A')

In [20]:
df['Content Rating'] = df['Content Rating'].fillna('N/A')
df['Current Ver'] = df['Current Ver'].fillna('N/A')
df['Android Ver'] = df['Android Ver'].fillna('N/A')

In [21]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [47]:
df[(df['Price'].str.startswith('$') == False) & (df['Price'].str.startswith('0') == False)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,N/A,"February 11, 2018",1.0.19,4.0 and up,N/A

In [55]:
df.loc[(df['Price'].str.startswith('$') == False) & (df['Price'].str.startswith('0') == False), 'Price'] = 0

In [56]:
df[(df['Price'].str.startswith('$') == False) & (df['Price'].str.startswith('0') == False)]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [67]:
df['Price'] = df['Price'].str.replace('$', '', regex=False)

In [71]:
df['Price'] = df['Price'].astype(float)

In [74]:
df['Currency'] = 'USD'

In [76]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Currency
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,USD
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,USD
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,USD
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,USD
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,USD

In [77]:
df.insert(8, 'Currency', df.pop('Currency'))

In [78]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Currency,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0.0,USD,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0.0,USD,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0.0,USD,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0.0,USD,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0.0,USD,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [80]:
df[df['Price'] > 0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Currency,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,4.99,USD,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,4.99,USD,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,4.99,USD,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
291,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,4.99,USD,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,Varies with device,"100,000+",Paid,3.99,USD,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10735,FP VoiceBot,FAMILY,N/A,17,157k,100+,Paid,0.99,USD,Mature 17+,Entertainment,"November 25, 2015",1.2,2.1 and up
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.4,35,2.4M,"1,000+",Paid,7.99,USD,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,Trine 2: Complete Story,GAME,3.8,252,11M,"10,000+",Paid,16.99,USD,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,"sugar, sugar",FAMILY,4.2,1405,9.5M,"10,000+",Paid,1.20,USD,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up
10798,Word Search Tab 1 FR,FAMILY,N/A,0,1020k,50+,Paid,1.04,USD,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up

In [91]:
df[df['Last Updated'].str.match(r'^[A-Z][a-z]+ \d{1,2}, \d{4}$') == False]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Currency,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,0.0,USD,N/A,"February 11, 2018",1.0.19,4.0 and up,N/A

In [97]:
df.loc[10472, 'Last Updated']

'1.0.19'

In [98]:
df.loc[10472, 'Last Updated'] = df.loc[10472, 'Genres']

In [99]:
df.loc[10472, 'Last Updated']

'February 11, 2018'

In [102]:
# Convert 'Last Updated' column to datetime
df['Last Updated'] = pd.to_datetime(df['Last Updated'], format='%B %d, %Y')

In [103]:
df['Last Updated']

0       2018-01-07
1       2018-01-15
2       2018-08-01
3       2018-06-08
4       2018-06-20
           ...
10836   2017-07-25
10837   2018-07-06
10838   2017-01-20
10839   2015-01-19
10840   2018-07-25
Name: Last Updated, Length: 10841, dtype: datetime64[ns]

In [104]:
# convert to ISO 8601
df['Last Updated'] = df['Last Updated'].dt.strftime('%Y-%m-%dT%H:%M:%S')

In [105]:
df['Last Updated']

0        2018-01-07T00:00:00
1        2018-01-15T00:00:00
2        2018-08-01T00:00:00
3        2018-06-08T00:00:00
4        2018-06-20T00:00:00
                ...
10836    2017-07-25T00:00:00
10837    2018-07-06T00:00:00
10838    2017-01-20T00:00:00
10839    2015-01-19T00:00:00
10840    2018-07-25T00:00:00
Name: Last Updated, Length: 10841, dtype: object

# 5- Export the pre processed file to csv and xlsx format

In [107]:
df.to_csv('exports/googleplaystore.csv')

In [108]:
df.to_excel('exports/googleplaystore.xlsx')